### ISSUE TITLE
Messes up folder icon on Anuppucin

### ISSUE THREAD

**Issue by Aeases** [LostPaul/obsidian-folder-notes#10]
Using the anuppucin theme the folder icons get messed up when using this plugin.

![image](https://user-images.githubusercontent.com/96164686/236361815-63960813-c894-4354-82d4-396975af35be.png)

I am using Windows 10, have tested on Windows 11.

**Comment by LostPaul** [comment]
Until I fix it you can disable this in the settings
![ScxxEmjRaWUJEXSFUR8s](https://user-images.githubusercontent.com/70213368/236429803-892e3730-afd6-4883-a3af-c99b0e55bc17.png)
Without it, it still prevents folder collapsing but not everywhere you click
https://user-images.githubusercontent.com/70213368/236436225-16ef1cd8-49c3-4979-8e8c-b681bb720bf6.mp4

**Comment by LostPaul** [comment]
Fixed with the latest release!
