### ISSUE TITLE
Bug: Folder-overview display error

### ISSUE THREAD

**Issue by likemuuxi** [LostPaul/obsidian-folder-notes#103]
When I set foldernote in a folder, the following situation occurs and the option does not work
![image](https://github.com/LostPaul/obsidian-folder-notes/assets/85612715/6ca1b9ce-99a4-4c7c-bea2-45387765b35c)

**Comment by mayurankv** [comment]
I also have this issue

**Comment by LostPaul** [comment]
Should be fixed with the next release
