### ISSUE TITLE
Opening folder note through path reopens hidden left sidebar

### ISSUE THREAD

**Issue by milan-tom** [LostPaul/obsidian-folder-notes#105]
When I click on a folder in a path that has a corresponding folder note, it takes me to the folder note but the left sidebar is also revealed even if it was hidden before. I understand that this is expected functionality for normal folders as the only real reason to click that folder name is to view it in the file explorer sidebar. However, this is annoying when you simply want to go to the folder note while keeping the sidebar hidden. Perhaps a keyboard combination with clicking the folder note in the path should replicate the current functionality and just clicking the folder note in the path should only go to the folder note without revealing the left sidebar.

# Steps to reproduce
- Turn open folder note through path setting on
- Hide left sidebar
- Open folder note through path
- View left sidebar reopened

**Comment by LostPaul** [comment]
Yeah this happens because the folder gets highlighted in the file explorer but I should be able to stop that like I did it with the folders that don't collapse when you only click on the name. Thanks for creating this issue I might be able to "fix" this tomorrow or at least in the next days.
