### ISSUE TITLE
Automatically add folder overview to new folder note

### ISSUE THREAD

**Issue by Kullenej** [LostPaul/obsidian-folder-notes#106]
Thank you for an amazing plugin – really appreciate this.

I have one problem though, and it might be just me who is doing something wrong, but whenever I create a new folder, I automatically get a new folder note. And I have even created a template that adds a button on the top with the plugin "Meta Bind" that can create a new note in that same file so I can populate the folder overview with new notes. BUT my problem is that I can't get the folder overview codeblock to be in the folder overview automatically. I have to create a new folder and then inside this new folder note, open the command palette and use the command "Insert folder overview". Can this be done automatically?

**Comment by LostPaul** [comment]
You should be able to just copy the codeblock that got created by the command and insert in the template you're using for new folder notes.


https://github.com/LostPaul/obsidian-folder-notes/assets/70213368/7ac6d795-9750-4403-a953-5aeef73fe228

**Comment by Kullenej** [comment]
Great, thanks! I just thought that each folder overview had a different "id", but they can share the same id then? I'll test it. Thank you!

**Comment by LostPaul** [comment]
I'm not sure but I think I added the ids to separate them from each other to add sometime in the future a feature to edit folder overviews from one file by using a command and selecting which one you want to edit. To make it easier to edit them on mobile.

**Comment by mayurankv** [comment]
Could the ids not be dispensed with in favour of using indexing by a combination of file path and specified config folder path? It seems weird to set an arbitrary id when unique identifiers exist.

**Comment by LostPaul** [comment]
I've added them because you can theoretically create multiple overviews with the same folder path in the same file and like that it's easier to manage them. It will also be easier to implement a better way to edit the overviews on mobile in the future.
