### ISSUE TITLE
remove `console.log` in `getExcludedFolder`

### ISSUE THREAD

**Issue by CatCodeMe** [LostPaul/obsidian-folder-notes#107]
there are so many debug log in console.
<img width="555" alt="image" src="https://github.com/LostPaul/obsidian-folder-notes/assets/11496772/1a5eabb9-8421-4d08-884e-9806f7038ae2">

**Comment by Djyp** [comment]
I was coming to create the same kind of issue.
It just keeps piling up and adding up in my console. It could mess with anything debugging I need to do about plugins or dataview loading on startup

**Comment by LostPaul** [comment]
Yeah sorry about that, this already has been removed by someone through a pull request but then a few days later I forgot to create a new release for Obsidian. They should now be gone with the latest plugin release.
