### ISSUE TITLE
Option: Disable auto focus new folder note

### ISSUE THREAD

**Issue by kevinkickback** [LostPaul/obsidian-folder-notes#115]
When "Automatically create folder notes" is enabled it will auto focus any newly created folder in the active leaf. I would like the ability to disable that. 

This makes it hard to perform actions in the background such as moving a file with templater (if a new folder is created in the process) or  using vault.createFolder in a script as it will pull focus.

Thanks for the consideration!

**Comment by LostPaul** [comment]
Done, this will be added in the next plugin release.
