### ISSUE TITLE
Feature Request: Canvas file as folder note

### ISSUE THREAD

**Issue by batrand** [LostPaul/obsidian-folder-notes#12]
Hey there! Many thanks for the plugin and keeping it up to date. 

I'd love to be able to use a canvas file as the folder note for a folder. That is, just like how in a Folder, a file called Folder.md is treated as the note for that folder, I'm hoping a Folder.canvas file would be treated in a similar manner.

My use case is that I have a folder of media files, and a canvas for layout out those media files. Right now, to get to the canvas, I need to expand the folder and click on the canvas. I'd like to be able to just click on the folder and see the canvas instead.

**Comment by LostPaul** [comment]
The next release will include this change took my way longer than expected though
