### ISSUE TITLE
"Delete folder note" removes note file permanently instead of moving it to the trash

### ISSUE THREAD

**Issue by evgeny-kim** [LostPaul/obsidian-folder-notes#120]
"Delete folder note" command says that folder note will be moved to the system trash.
But instead, the corresponding file is deleted permanently.

OS Windows. Please see the event log attached:

![delete](https://github.com/LostPaul/obsidian-folder-notes/assets/122977221/a054e333-7c18-437c-88c7-64608265866a)

**Comment by LostPaul** [comment]
Sorry for the late fixed but as mentioned in the release notes of the new release it won't take that long anymore in the feature and thanks for reporting the bug. Now it works exactly like it does in Obsidian for normal files when they get deleted.
