### ISSUE TITLE
RTL Folder titles

### ISSUE THREAD

**Issue by yonatankremer** [LostPaul/obsidian-folder-notes#128]
Hey, 
Since the new Obsidian update (1.6) with reworked RTL, the plugin causes RTL folder titles in the sidebar align to the right, causing odd inconsistency. It's 100% the plugin, tried isolating the cause. It doesn't happen with single notes too. Thanks!

**Comment by LostPaul** [comment]
Thanks for the bug report, I'll try to fix it soon but in the meantime you can temporarily fix it yourself by enabling this setting
![Hzcs1wqAYGaJWLUbxkgX](https://github.com/LostPaul/obsidian-folder-notes/assets/70213368/7fef4aed-c83d-421e-a411-87d8b2a1372f)

**Comment by LostPaul** [comment]
This should be fixed with the next plugin release.
