### ISSUE TITLE
FR：Disable folder collapsing when clicking folder in the path

### ISSUE THREAD

**Issue by zhaihao** [LostPaul/obsidian-folder-notes#13]
the option "Disable folder collapsing" is not working for clicking folder in the path

**Comment by LostPaul** [comment]
> the option "Disable folder collapsing" is not working for clicking folder in the path

Because that would remove the highlight function but I'll add an extra setting for the path soon

**Comment by LostPaul** [comment]
Actually it doesn't collapse the folder could you provide a video of what your issue exactly is?

**Comment by zhaihao** [comment]
> Actually it doesn't collapse the folder could you provide a video of what your issue exactly is?

Ah！We are not discussing the same issue. "Disable folder collapsing" works fine when I click folder embed link in some note.

https://github.com/LostPaul/obsidian-folder-notes/assets/4202032/512386eb-04e5-4ce3-b069-d8ad715be6e0
