### ISSUE TITLE
Folder note not hidden in android app

### ISSUE THREAD

**Issue by ShazaLee** [LostPaul/obsidian-folder-notes#135]
When using the Android app synced to my normal Windows desktop I can see the "hidden" folder note, this is not the case on Windows

**Comment by LostPaul** [comment]
Is it alright now? Are you sure the vault got synced? You can check if the setting got synced here:

![image](https://github.com/user-attachments/assets/be1dcc07-d3f0-44e6-b854-f06e34ba9daa)

Or what's the problem you're having?
