### ISSUE TITLE
delete file 

### ISSUE THREAD

**Issue by Andry042023** [LostPaul/obsidian-folder-notes#142]
Good day! When we select delete, it says that it will delete to the system folder, but instead it will delete irrevocably that it cannot be found!
![image](https://github.com/user-attachments/assets/20181446-7c4a-4f75-b03e-8b0be119db0f)

**Comment by LostPaul** [comment]
Sorry about that I've already fixed it a few months ago but because of how I released new versions and because I was busy with other stuff it took way too long but it shouldn't take that longer anymore. (see the release notes of the latest version)
