### ISSUE TITLE
Can`t safe Template Path anymore

### ISSUE THREAD

**Issue by erikcestner** [LostPaul/obsidian-folder-notes#146]
i made a new Folder Note Template, wanted  to change the Path.
It doesnt`t safe the path of the Template.
When i try to safe it under Template path, i can put in the path in, but as soon as i leave the settings window, the path is gone. No way to safe it.
Restart, or even brand new Vault it just doesnt work anymore for me...
i checked what i could, but couldn`t make it out...

**Comment by nestor50** [comment]
Same here.... :-(

**Comment by NULLx76** [comment]
Having the same issue

**Comment by erikcestner** [comment]
> Does this release fix this issues? https://github.com/LostPaul/obsidian-folder-notes/releases/tag/1.7.30-5-beta

Yes, i replaced the old  main.js with the new one, seems to work! Thank you for the fix my man! Appreciate it.stay safe
