### ISSUE TITLE
Outline tab collapse-icon position is being changed in Obsidian 1.3.2

### ISSUE THREAD

**Issue by trainbuffer** [LostPaul/obsidian-folder-notes#15]
-   Create new vault
-   Install Obsidian-Folder-Notes
-   Make a few folders
-   Make a new note with the contents of: [https://help.obsidian.md/Editing+and+formatting/Basic+formatting+syntax](https://help.obsidian.md/Editing+and+formatting/Basic+formatting+syntax)
- View the _Outline_ tab.

The collapse icon in the Files tab is fine, but in the Outline tab it isn't aligned. 

![ng](https://github.com/LostPaul/obsidian-folder-notes/assets/3751726/a8bba7bc-9d9b-4469-8679-f8ebd1943a91)

Turn on restricted mode and close/open that vault. The icons are in the correct position. 

![ok](https://github.com/LostPaul/obsidian-folder-notes/assets/3751726/d94ce9a7-5d22-4255-a141-a778b2d4ee1d)

It seems to be this 4px here in styles.css is affecting the Outline tab instead of only the Files list.
```
.fn-whitespace-stop-collapsing .collapse-icon {
    margin-top: 4px;
}
```
Thanks! 

```
SYSTEM INFO:
	Obsidian version: v1.3.2
	Installer version: v1.2.8
	Operating system: Windows 10 Pro 10.0.22621
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Folder notes v1.2.2
```

**Comment by LostPaul** [comment]
Fixed with the latest release!
