### ISSUE TITLE
Folder notes broken after update(1.7.4)

### ISSUE THREAD

**Issue by afrolino02** [LostPaul/obsidian-folder-notes#161]
I can't select the note folders in the browser, or select it in make.md spaces, even there's an error in the obsidian's startup "Could not open "notes folder"" 

# steps to reproduce this issue 

1. Open obsidian
2. Select a created note folder 
3. It doesn't open with the plugin
4. Appears a pop-up with the notice that said  note folders couldn't startup correctly

**Comment by sigrunixia** [comment]
I am not able to reproduce. I *think* you asked this question on reddit too?

Can you reproduce in the [sandbox vault](https://help.obsidian.md/Getting+started/Sandbox+vault)?

**Comment by cbzen** [comment]
Same issue with a different scenario. I am installing it for the first time with Obsidian 1.7.4 and the plugin will not enable. Displays the error, "Failed to load plugin 'folder-notes".

**Comment by kabokabeso** [comment]
At my Value on IPhone 14,it also does not work anymore. When I try to load folder notes it says “failed to load plugin “folder-notes “”. I also use the plugin remoty safe. Maybe it has to do something with this? 
Did not check on windows yet.

**Comment by moiseszarzar** [comment]
> At my Value on IPhone 14,it also does not work anymore. When I try to load folder notes it says “failed to load plugin “folder-notes “”. I also use the plugin remoty safe. Maybe it has to do something with this? For me only version 1.7.32 is available. Did not check on windows yet.

I'm having same problem in Windows. If this plugin was the solution to AidenLx's Folder Note broken, I think we have a new plugin broken.

**Comment by LostPaul** [comment]
It works fine for me on windows and with an Iphone 12 without other plugins but I'll look into this later today.

**Comment by moiseszarzar** [comment]
> It works fine for me on windows and with an Iphone 12 without other plugins but I'll look into this later today.

Maybe it has conflicts with other plugins. I have a great number of plugins enabled in my vault. 

But you will test in yours.

Depending on your results, i can post my console error messages later.

**Comment by LostPaul** [comment]
I've the issue when I use make.md, it has something to do with the file explorer view.

**Comment by moiseszarzar** [comment]
I think you need to see what has been changed in file explorer in the Obsidian version 1.7.4

**Comment by nicokaiser** [comment]
I do not know if the is related, but starting from version 1.7.4, the plugin occasionally stops working after some time. Disabling and re-enabling the plugin fixes it, but it happens again after some time (I could not figure out a pattern yet).

**Comment by moiseszarzar** [comment]
> I've the issue when I use make.md, it has something to do with the file explorer view.

Have you seen this (maybe related with the problem) ?

https://docs.obsidian.md/Plugins/Guides/Understanding+deferred+views

**Comment by LostPaul** [comment]
> > I've the issue when I use make.md, it has something to do with the file explorer view.
> 
> Have you seen this (maybe related with the problem) ?
> 
> https://docs.obsidian.md/Plugins/Guides/Understanding+deferred+views

Yeah that might be the problem

**Comment by LostPaul** [comment]
I've got it working now but the css classes don't get applied anymore so still not done.

**Comment by afrolino02** [comment]
> I am not able to reproduce. I _think_ you asked this question on reddit too?
> 
> Can you reproduce in the [sandbox vault](https://help.obsidian.md/Getting+started/Sandbox+vault)?

The problem happened because Make.md doesn't support it, by the way the plugin still buggy, but it works, I have a problem with the file explorer that happened the name folder note shows the file folder, i meant, if the folder note calle "name1", the file with the folder note name is showed

**Comment by sql99** [comment]
Have the same issue. With restart of plugin is fixed.

**Comment by LostPaul** [comment]
Make.md fixed it in one of the latest updates
