### ISSUE TITLE
[Bug]: Sorting problem of Folder Overview

### ISSUE THREAD

**Issue by likemuuxi** [LostPaul/obsidian-folder-notes#169]
When the File depth is greater than 1, the sorting of deeper files becomes invalid for Folder Overview

![image](https://github.com/user-attachments/assets/069c0e2e-5165-4578-8fe2-4b4f3ba20adb)

**Comment by likemuuxi** [comment]
Only the contents of folders with a depth of two levels can be displayed
![image](https://github.com/user-attachments/assets/031d407d-b5ac-4ade-b305-a3d3a1288365)
![image](https://github.com/user-attachments/assets/5a94563d-a770-4ac2-846c-a1b79fd822c5)

Files that start with two digits still cannot be sorted in ascending order by name
![image](https://github.com/user-attachments/assets/6068c837-3223-475f-8d7d-b7d50dd6e864)

**Comment by hsandt** [comment]
Confirmed in v1.7.35
![Image](https://github.com/user-attachments/assets/dc231206-a5e0-495f-a160-3444e4f7446d)

The order is not just "invalid", it is truly in Descending order on level 2. We should rename the issue title to reflect that.

**Comment by LostPaul** [comment]
> Confirmed in v1.7.35 ![Image](https://github.com/user-attachments/assets/dc231206-a5e0-495f-a160-3444e4f7446d)
> 
> The order is not just "invalid", it is truly in Descending order on level 2. We should rename the issue title to reflect that.

Could you try it using the beta version? https://github.com/LostPaul/obsidian-folder-notes/releases/tag/1.7.30-26-beta

Also thanks for all the issues and comments but currently I don't have that much time but I'll try to fix or at least reply to most of them in a few days or weeks.
