### ISSUE TITLE
Feature: Folder Overview, File Explorer: Collapse by default

### ISSUE THREAD

**Issue by xorvoid** [LostPaul/obsidian-folder-notes#180]
I'd like to have the File Explorer collapse all by default in the Folder Overview.

Is there an option for this feature already? If not, I'm happy to contribute it with a little guidance.

**Comment by LostPaul** [comment]
Merged

**Comment by warm-july** [comment]
hi looks like this is implemented, but I couldn't find it in the settings, can you help? Thank you!
