### ISSUE TITLE
autoCreateFocusFiles is not making it into main.js

### ISSUE THREAD

**Issue by punassuming** [LostPaul/obsidian-folder-notes#183]
Somewhere in the compilation step, the main.js compilation is dropping some of the parameters set conditionally within settings.autoCreate. 

![image](https://github.com/user-attachments/assets/b163dc90-3fa9-4dfc-9336-656324abf016)

Any idea what could be causing this?

**Comment by punassuming** [comment]
Looking into it, even though your manifest was updated just recently, your git tags is from a long time ago:

![image](https://github.com/user-attachments/assets/e0c2d3c2-bca2-436b-980a-b040cf4f672f)

**Comment by LostPaul** [comment]
Yeah because I haven't finished the next release yet because I had some issues and I only released bug fixes.
