### ISSUE TITLE
Recursive Excluded Folder

### ISSUE THREAD

**Issue by Kageetai** [LostPaul/obsidian-folder-notes#19]
First, wonderful plugin, definitely more feature complete and actively being developed, than some other of the many folder note plugins out there!

But I am not sure whether I understand the feature to exclude folders fully, or maybe I am missing something. So my question is hopefully quite straightforward:

**How do I exclude a folder and all its subfolders?**

I tried just adding `/*` to a folder, but doesn't seem to work. The new regex feature just now doesn't seem to achieve that either, right?

Thanks in advance

**Comment by LostPaul** [comment]
The wildcard is actually only for the name of the folder and not the path
![p3VNY92RnCOGWVcAa7km](https://github.com/LostPaul/obsidian-folder-notes/assets/70213368/8a394047-f38b-4a6b-8734-3987f89ab466)
![image](https://github.com/LostPaul/obsidian-folder-notes/assets/70213368/2e01d222-ab46-476c-ae48-a00c192d568a)

**Comment by LostPaul** [comment]
and I just saw I made a typo in the setting modal lol

**Comment by Kageetai** [comment]
That might explain why I don't see that setting 😅

**Comment by LostPaul** [comment]
> That might explain why I don't see that setting 😅 

Wdym I just meant the name of the modal

**Comment by Kageetai** [comment]
Hmm, the setting is there now, weird. I am sure I checked yesterday and thought it wasn't there. Thanks anyway

**Comment by LostPaul** [comment]
> Hmm, the setting is there now, weird. I am sure I checked yesterday and thought it wasn't there. Thanks anyway

Probably because it changed to a pattern and the settings modal is different than from the folder settings modal because the pattern is only for the name and it doesn't involve the path so it can't know if for example a folder is a subfolder of the excluded folders/folder through the pattern.
![oq6XY3yQ2ArTa3mwghTp](https://github.com/LostPaul/obsidian-folder-notes/assets/70213368/348145aa-4262-41ef-b35a-591dfb5a8761)

**Comment by LostPaul** [comment]
I'll try to explain it better in the next release

**Comment by Kageetai** [comment]
Ah right, maybe I was looking at the other settings momentarily. Thx for clarifying
