### ISSUE TITLE
Not working on MacOS

### ISSUE THREAD

**Issue by jwierzbo** [LostPaul/obsidian-folder-notes#2]
Plugin is not working on macOS and iOS.
After right click on folder -> Create Folder Note nothing happen...

**Comment by LostPaul** [comment]
Could you provide a video?

**Comment by jwierzbo** [comment]
On macOS it is not working with CTRL + click.
But alt+click works as expected (once changed in the settings)

**Comment by LostPaul** [comment]
> On macOS it is not working with CTRL + click. But alt+click works as expected (once changed in the settings)

@jwierzbo Fixed
