### ISSUE TITLE
 "Turn into folder note" and more.

### ISSUE THREAD

**Issue by EarthHealer** [LostPaul/obsidian-folder-notes#20]
1. Prompt function:

A is a folder containing two notes "B.md" and "A.md".

"b.md" is a general note and "A.md "is a "FolderNote".

Use "Turn into folder note" on "b.md" , so that the existing A folder and "A.md" are modified equally.

But I don't want to change the original folders A and A.md.

I need it to tell me that "A.md exists" or "A Folder has have the note A.md", to give me a chance to quit.

2. The function of converting existing general notes into FolderNote.

Take the existing note "b.md" and create folder b, move "b.md" into folder b.

Many notes are generated directly in a folder, I need to manually change to "FolderNote".

I want to implement a folder that contains only one note.

Prefer to integrate "xpgo →folder-note" and "Note folder autorenamer".

**Comment by LostPaul** [comment]
The create folder note now creates a folder with the note as the folder note and the turn into folder note option now prompts a modal on first time usage for if you want to rename the existing folder note or if you want to cancel it.
![xeQoG8JRsF1dBuQysquW](https://github.com/LostPaul/obsidian-folder-notes/assets/70213368/b4c98cb1-c595-4c5c-bc3f-fa86d2efd305)
![EG17gxOxtkXQmjjqH0Wf](https://github.com/LostPaul/obsidian-folder-notes/assets/70213368/e27b48e4-a3f3-4be2-b11d-5193f9e6aca6)
![hMTxPaFMgQsp8wB0jvHg](https://github.com/LostPaul/obsidian-folder-notes/assets/70213368/6559b12a-d024-4411-8463-61ef2518edc6)

**Comment by EarthHealer** [comment]
YEAH!!!
