### ISSUE TITLE
the new blank note with the same name overwrites the existing note. 

### ISSUE THREAD

**Issue by EarthHealer** [LostPaul/obsidian-folder-notes#21]
When I right-click on an existing Note and use the "Create Folder Note" command, the newly created blank note overwrites the existing note. 
Previously, the same would have happened. 
When I open the "Note Folder Autorename" "Folder notes" plugin at the same time, for a particular existing Note, even if I execute "Make-This-Note-A-folder-note"(belonging to the "Note Folder Autorename"), "Folder Notes" also takes precedence over the "Create-Folder-Note" action, creating a blank "Note" with the same name.

Also, the new blank note overwrites the existing note. Therefore, I closed folderNotes.

**Comment by LostPaul** [comment]
Are you on the latest plugin version?

**Comment by LostPaul** [comment]
Because it works fine for me if I've understood you correctly.

https://github.com/LostPaul/obsidian-folder-notes/assets/70213368/13114bc2-b158-4cc3-aee9-48d612c23561

**Comment by EarthHealer** [comment]
I have updated to the latest version via automatic upgrade.

Same operation with different results?

________________________________
发件人: Lost Paul ***@***.***>
发送时间: 2023年6月18日 21:27
收件人: LostPaul/obsidian-folder-notes ***@***.***>
抄送: Earth Healer ***@***.***>; Author ***@***.***>
主题: Re: [LostPaul/obsidian-folder-notes] the new blank note with the same name overwrites the existing note. (Issue #21)


Because it works fine for me if I've understood you correctly.

https://github.com/LostPaul/obsidian-folder-notes/assets/70213368/13114bc2-b158-4cc3-aee9-48d612c23561

―

**Comment by LostPaul** [comment]
What are your active plugins?

**Comment by EarthHealer** [comment]
________________________________
发件人: Lost Paul ***@***.***>
发送时间: 2023年6月19日 12:42
收件人: LostPaul/obsidian-folder-notes ***@***.***>
抄送: Earth Healer ***@***.***>; Author ***@***.***>
主题: Re: [LostPaul/obsidian-folder-notes] the new blank note with the same name overwrites the existing note. (Issue #21)


What are your active plugins?

―

**Comment by EarthHealer** [comment]
This is true even if I close all the community plugins and keep only FolderNotes.
________________________________
发件人: Lost Paul ***@***.***>
发送时间: 2023年6月19日 12:42
收件人: LostPaul/obsidian-folder-notes ***@***.***>
抄送: Earth Healer ***@***.***>; Author ***@***.***>
主题: Re: [LostPaul/obsidian-folder-notes] the new blank note with the same name overwrites the existing note. (Issue #21)


What are your active plugins?

―

**Comment by LostPaul** [comment]
> This is true even if I close all the community plugins and keep only FolderNotes.
Can you try this in the sandbox vault and send a video of it?

**Comment by LostPaul** [comment]
It already does that but thanks!
![yfhtfcJlSsX8oMnS0HWl](https://github.com/LostPaul/obsidian-folder-notes/assets/70213368/78d67da7-0283-438d-aeb8-ecea78745030)

**Comment by EarthHealer** [comment]
thank you for you grate job.
________________________________
发件人: Lost Paul ***@***.***>
发送时间: 2023年6月20日 3:21
收件人: LostPaul/obsidian-folder-notes ***@***.***>
抄送: Earth Healer ***@***.***>; Author ***@***.***>
主题: Re: [LostPaul/obsidian-folder-notes] the new blank note with the same name overwrites the existing note. (Issue #21)


It already does that but thanks!
[yfhtfcJlSsX8oMnS0HWl]<https://user-images.githubusercontent.com/70213368/246918463-78d67da7-0283-438d-aeb8-ecea78745030.png>

―
