### ISSUE TITLE
[FR] - Suggestions for the folder overview

### ISSUE THREAD

**Issue by ndharari** [LostPaul/obsidian-folder-notes#23]
I love the new addition! I would ask for two things:

1. Can we have the title as [Folder name] Overview?
2. I was using upto now the Zoottelkeeper plug-in, but this one seems much more clean! However, with yout plugin links will not appear in the graph view. You know if we can change that?

Thanks for the great work!

**Comment by LostPaul** [comment]
The first point is now possible with the latest release and I'm not sure about the second if it's possible but I can try when I've more time.

**Comment by menagerie198** [comment]
Might I add a related request here?
When 'file depth' is set at 1, we only get links to the files in the folder...
- could we have the sub-folders showing up as links also?

also... thanks for the on-going great work!

**Comment by LostPaul** [comment]
> Might I add a related request here? When 'file depth' is set at 1, we only get links to the files in the folder...
> 
>     * could we have the sub-folders showing up as links also?
> 
>     * currently 'file depth' at 2 shows all the files in the sub-folders - I just want links to sub-folder (if they have a Folder Note)
>       Cheers
> 
> 
> also... thanks for the on-going great work!

Folders that had a folder note already showed up as a link but now there is a option to include subfolders in the list when the file depth is set to 1 previously that wasn't the case because I removed folders that had no items (the files) in it.

**Comment by menagerie198** [comment]
Thanks - that does the trick - and FAST!
