### ISSUE TITLE
last of a simple example plus issue with include types

### ISSUE THREAD

**Issue by pcause** [LostPaul/obsidian-folder-notes#24]
LOVE including the folder contents display.  2 things:

- there should be a note in the README that to use the folder overview you use '''folder-overview  There was nothing about this and the video on discord doesn't show the tag.

- when I click the </> to get option and then go to the include types I see folder and markdown but the list also shows a pdf file I have.  that is good for me, but since the list doesn't have pdf it is confusing.  also, when I click the + at the end of the line to add a folder type I get a dropdown with canvas and a +.  when I click the + nothing happens.  Am I supposed to be able to add filetypes?

**Comment by LostPaul** [comment]
I'll update the readme soon it's currently outdated since months.
Secondly I've added dropdown options for different file types so that you can decide if you want to include pdfs or other file types in the list.

**Comment by pcause** [comment]
thanks.  it *was* listing pdf's without me setting anything.
