### ISSUE TITLE
Folder Overview depth 1

### ISSUE THREAD

**Issue by Kageetai** [LostPaul/obsidian-folder-notes#25]
The new folder overview seems great (even though a bit hidden) :)
Just one thing, and maybe I don't understand the options yet: A depth of 1 doesn't seem. to render anything:
<img width="684" alt="Screenshot 2023-07-09 at 21 39 30" src="https://github.com/LostPaul/obsidian-folder-notes/assets/1738309/1bd04ede-0bfb-49a1-b4a2-ab6ab40187c3">
I can only set it to two to get two levels deep overview:
<img width="712" alt="Screenshot 2023-07-09 at 21 39 14" src="https://github.com/LostPaul/obsidian-folder-notes/assets/1738309/c7e5a98c-ae6e-46d5-8bb3-49e6c5a4896b">
But I wan't the same as the other plugin above.
Thanks

**Comment by LostPaul** [comment]
Enable both of the options 
![image](https://github.com/LostPaul/obsidian-folder-notes/assets/70213368/b4514e15-dd98-4cb8-903a-f603da153966)

**Comment by Kageetai** [comment]
Ah I see thanks, that's a rather confusingly phrased setting then. Those folders are not empty in my case

**Comment by LostPaul** [comment]
It's empty in the folder overview list when you don't increase the depth do you have a better suggestion?

**Comment by Kageetai** [comment]
Not sure what would fit better, but "empty folder" doesn't really fit, as the folders themselves are not empty. How about "folders without children in the list" or so?!
