### ISSUE TITLE
Canvas folder note opens as markdown

### ISSUE THREAD

**Issue by anareaty** [LostPaul/obsidian-folder-notes#28]
When I create canvas folder note and open it from clicking on folder, it renders as markdown note with json code instead of canvas format.

![Screenshot_4](https://github.com/LostPaul/obsidian-folder-notes/assets/55949830/b9edb775-9709-4639-9ed4-bf0092e9b308)

**Comment by LostPaul** [comment]
I can't reproduce it; are you on the latest plugin version? If yes could you provide a video?
