### ISSUE TITLE
Comparison with similar plugin

### ISSUE THREAD

**Issue by alexey-zaharchenko** [LostPaul/obsidian-folder-notes#3]
Hi, can you add comparison with https://github.com/aidenlx/alx-folder-note ?

**Comment by LostPaul** [comment]
> Hi, can you add comparison with https://github.com/aidenlx/alx-folder-note ?

To the readme?
Sure, I talked about in issue #2 see https://github.com/LostPaul/obsidian-folder-notes/issues/1#issuecomment-1483934507

**Comment by brimwats** [comment]
> To the readme?


A chart or a table would be very informative, yes! Excited to try this version out!

**Comment by LostPaul** [comment]
The ReadMe is very outdated since this issue many things have been added that are unique and I'll update the ReadMe soon.
