### ISSUE TITLE
not excluding a folder pattern

### ISSUE THREAD

**Issue by pcause** [LostPaul/obsidian-folder-notes#30]
i have entered _attachments" as my exclude pattern as per this:

![image](https://github.com/LostPaul/obsidian-folder-notes/assets/1071479/69465128-35ad-4e67-bfa5-8098bfd9f8f3)

but when I create a folder note for a folder with an _attachments sub folder I get this:

![image](https://github.com/LostPaul/obsidian-folder-notes/assets/1071479/c17469ae-b4ec-4256-88f0-0746c2b25a34)

here is the source view of the folder note

![image](https://github.com/LostPaul/obsidian-folder-notes/assets/1071479/ba2ce1f2-d161-43f8-a0f1-fc188cdf59aa)

**Comment by LostPaul** [comment]
The plugin lacks documentation. I'll change that soon but when you click on the button to edit the excluded folder it no where shows that it will be excluded from the folder overview. It will also only change to a pattern if you add * at the beginning or at the end or {regex} at the beginning. I've added now that you can now exclude it from the folder overview.

**Comment by pcause** [comment]
downloaded the new version and same thing happen

![image](https://github.com/LostPaul/obsidian-folder-notes/assets/1071479/5dd1d976-2b79-4498-81e3-86b713b652ca)

![image](https://github.com/LostPaul/obsidian-folder-notes/assets/1071479/e0f6bcdc-938d-4b71-bb5f-54a846679908)

![image](https://github.com/LostPaul/obsidian-folder-notes/assets/1071479/428aa6e4-b946-49ea-a01d-99468ac58055)

i deleted the note that was there, restarted after making all the settings and recreated the note.  I am on the latest insider build, btw

**Comment by LostPaul** [comment]
Not sure why it's not working I'll try to fix that now but "{regex}_attachments" should work

**Comment by pcause** [comment]
changed to *_attachments and it still shows that folder.

**Comment by LostPaul** [comment]
It should work now.

**Comment by pcause** [comment]
nope.  same thing

**Comment by LostPaul** [comment]
Did you enable this?
![hcDDxnERQBlYyB1gECdp](https://github.com/LostPaul/obsidian-folder-notes/assets/70213368/77a74c7f-4df9-4b77-bf20-38bbc9d686f9)

**Comment by pcause** [comment]
yes

![image](https://github.com/LostPaul/obsidian-folder-notes/assets/1071479/15b61eb5-063c-41ba-9980-a4713338ce04)

**Comment by pcause** [comment]
also tried *_attachments* with no luck

**Comment by LostPaul** [comment]
> yes
> 
> 
> 
> ![image](https://github.com/LostPaul/obsidian-folder-notes/assets/1071479/15b61eb5-063c-41ba-9980-a4713338ce04)
> 
> 

And you have the latest plugin version?

**Comment by pcause** [comment]
1.4.8

**Comment by LostPaul** [comment]
I see it didn't work because it was in a subfolder and I forgot to also create it for subfolders. It should work now

**Comment by pcause** [comment]
fixed.  thanks for the effort and the great plugin.
