### ISSUE TITLE
allow collapsing of folder contents display

### ISSUE THREAD

**Issue by pcause** [LostPaul/obsidian-folder-notes#31]
The generated folder note doesn't allow the displayed folders in the folder note to be collapsed.  so if I have 5 folders and each 50 notes, the display is hard to work with.  can you generate markdown headers to allow the various folders to be collapsed/expanded.  Also an option in the ```folder-overview  settings have an option to show folders collapsed other than the top level.  If I have folder X and 3 subfolders, A,B,C I would get the following collapsed:

note1
note2
..
note-n
A
B
C

**Comment by LostPaul** [comment]
Is the new explorer style for the folder overview good enough for you or do you still want it for the list style?

**Comment by pcause** [comment]
not sure what you are asking.  the stule looks good but still no ability to collapse/expand the folders.  I do have the "disable folder collapsing"  not set (so it should allow).

**Comment by LostPaul** [comment]
https://github.com/LostPaul/obsidian-folder-notes/assets/70213368/ac7a12de-b61e-4c9d-af4f-88955ada2055

**Comment by LostPaul** [comment]
> mine looks like:
> 
> 
> 
> ![image](https://github.com/LostPaul/obsidian-folder-notes/assets/1071479/088d3ee3-5d8d-400b-81c9-afda2113de47)
> 
> 
> 
> and here is the source
> 
> 
> 
> ![image](https://github.com/LostPaul/obsidian-folder-notes/assets/1071479/f83da621-bb02-4bd6-bd38-eb68ec2423c7)
> 
> 

Click on the edit button on the right or change list to explorer.
