### ISSUE TITLE
folder note command disappear

### ISSUE THREAD

**Issue by Morganwan90** [LostPaul/obsidian-folder-notes#32]
im using 1.4.2. I just find that there is no command for folder note.. dont know why

<img width="1265" alt="截图_20230810131157" src="https://github.com/LostPaul/obsidian-folder-notes/assets/61633409/835cfbfa-09c9-49f9-8148-9a9ffb090e52">

**Comment by LostPaul** [comment]
What commands do you want?

**Comment by Morganwan90** [comment]
> What commands do you want?

I remember there used to be commands like "make current note as folder note," right?

**Comment by Morganwan90** [comment]
> > What commands do you want?
> 
> I remember there used to be commands like "make current note as folder note," right?

<img width="672" alt="截图_20230810191031" src="https://github.com/LostPaul/obsidian-folder-notes/assets/61633409/7c53150c-bf7a-4dc6-a21f-7c4a9c8a2b7a">

I use the commands in quickadd plugin.. but now I couldn't find those commands now.. is this a bug?

**Comment by LostPaul** [comment]
It never existed for this plugin, in the screenshot is a different plugin but the command will be available with the next update.
