### ISSUE TITLE
version 1.5.9 not loading

### ISSUE THREAD

**Issue by menagerie198** [LostPaul/obsidian-folder-notes#33]
I am having a problem loading the latest version. 
In the Obsidian 'Community plugins' modal I click 'update', I get a 'successfully installed plugin' notification, but the installed version still shows as '1'5.8', and the 'update' button remains

**Comment by LostPaul** [comment]
> I am having a problem loading the latest version. 
> 
> In the Obsidian 'Community plugins' modal I click 'update', I get a 'successfully installed plugin' notification, but the installed version still shows as '1'5.8', and the 'update' button remains

I had the same issue but it should still've installed 1.5.9 not sure why it's happening but even with a way older installation of the plugin I get 1.5.8 displayed as installed.

**Comment by LostPaul** [comment]
For some reason it still had the old version in the manifest I updated it now so it should work but I'm not sure if the main.js is right but I'm going to release a new version soon anyway.
