### ISSUE TITLE
Canvas turned into Folder Note doesn't show as a canvas when reopened

### ISSUE THREAD

**Issue by aliceinblunderland0** [LostPaul/obsidian-folder-notes#34]
Hello, this is a very useful plugin that suits my needs very well. However, there seems to be a bug: when turning a canvas note into the folder note, everything seems to initially work, but whenever the note is reloaded, it's viewed as a normal text note instead of a canvas note. Would this be a hard bug to fix?

**Comment by aliceinblunderland0** [comment]
https://github.com/LostPaul/obsidian-folder-notes/assets/142273759/1768dbfd-3882-4977-a2ab-7175d2e7a566

Here you go, hope it's clear enough

**Comment by LostPaul** [comment]
Should be fixed now!
