### ISSUE TITLE
[Bug] Not replacing folder name with front matter when folder note filename is fixed.

### ISSUE THREAD

**Issue by merrkry** [LostPaul/obsidian-folder-notes#35]
When 'Folder Note Name' is set to a fixed value (e.g. `_about_.md`) instead of `{{folder_name}}`, integration with front matter tile will not work. Filename in file explorer can't be replaced but the path above title seems to work fine.

<img width="1280" alt="image" src="https://github.com/LostPaul/obsidian-folder-notes/assets/124278440/452ed0d1-010c-4b98-a9f0-b8dbda7cc975">
<img width="1280" alt="image" src="https://github.com/LostPaul/obsidian-folder-notes/assets/124278440/c5397159-279c-4c74-bb34-15bf1d351534">
<img width="1280" alt="image" src="https://github.com/LostPaul/obsidian-folder-notes/assets/124278440/833d1b37-f98d-48df-a8b8-7c1ad17d03ed">

**Comment by LostPaul** [comment]
The frontmatter title plugin has to be enabled before enabling the integration or you restart Obsidian after enabling the setting.

**Comment by LostPaul** [comment]
> > The frontmatter title plugin has to be enabled before enabling the integration or you restart Obsidian after enabling the setting.
> 
> I tested after restart so I am sure it's a bug. Please tell me if you need more information to reproduce it.

Well a video with a new sandbox vault would be nice

**Comment by merrkry** [comment]
I started a sandbox vault, downloaded the two plugins and began recording. Here's the video:

https://github.com/LostPaul/obsidian-folder-notes/assets/124278440/ecd0ef90-77c1-4e77-b092-ff8014a7da37

You can see the folder name in explorer panel remains unchanged after modifying `folder note name` no matter how I edit the frontmatter value.

**Comment by LostPaul** [comment]
This should be fixed now.
