### ISSUE TITLE
Documentation of Settings?

### ISSUE THREAD

**Issue by judisohn** [LostPaul/obsidian-folder-notes#36]
I don't normally create issues for questions. Apologies but I didn't see a better way to contact the developer.

I've had this plugin installed for a while. But there seems to be no documentation or explanation of all the Settings. Especially the "Folder Overview" behind the "Manage" button. Can that be explained, please? Thanks.

**Comment by nevir** [comment]
I am also confused about what Folder Overview does (seems like it's useful for generating indexes of folders and whatnot; but it's unclear how it works - the settings seem to not affect anything obvious)

**Comment by nevir** [comment]
Aha: From [digging around the source](https://github.com/LostPaul/obsidian-folder-notes/blob/ce21b2ebc015c16640f498acaaab6ff7579cc24c/src/main.ts#L162), you need to insert a `folder-overview` code block:

<pre>
```folder-overview
```
</pre>

**Comment by LostPaul** [comment]
Is anything else important missing in the docs? A few weeks ago I explained most of the features here: https://lostpaul.github.io/obsidian-folder-notes/

**Comment by judisohn** [comment]
Thank you @LostPaul - this was very helpful and I'm starting to transition from Waypoint to Folder Notes for my Folder Note content. The documentation was helpful but still has some gaps I'd love to understand:

- What does "Folder Path for the overview" mean/do? It might be helpful if you outlined each item in the setting page with some additional explanation. Once I understand it, I'm happy to help with the [documentation](https://github.com/LostPaul/obsidian-folder-notes/tree/main/docs/docs). 
- If a subfolder is marked to Exclude or moved, is there a command to reset the overview? (I asked in a different open issue). I'm seeing that the folder overview is not updating after I've added it to a Folder note on a parent folder and I'm not clear if I'm missing something based on the documentation.

Thanks!
