### ISSUE TITLE
template not being applied

### ISSUE THREAD

**Issue by pcause** [LostPaul/obsidian-folder-notes#37]
From a folder-note i click a heading for a folder and a new folder note is created.  However the template I specified in settings isn't applied.  I get an empty note.  The name of the template in the settings is correct.  This is the content of the template:

![image](https://github.com/LostPaul/obsidian-folder-notes/assets/1071479/9282e43a-5eb4-4269-b00b-f2692d3c3a32)

If I then  use the templater command to insert the template all looks good.

**Comment by LostPaul** [comment]
> From a folder-note i click a heading for a folder and a new folder note is created. However the template I specified in settings isn't applied. I get an empty note. The name of the template in the settings is correct. This is the content of the template:
> 
> ![image](https://user-images.githubusercontent.com/1071479/261009898-9282e43a-5eb4-4269-b00b-f2692d3c3a32.png)
> 
> If I then use the templater command to insert the template all looks good.
Did you restart Obsidian?
![image](https://github.com/LostPaul/obsidian-folder-notes/assets/70213368/0e30d5d3-d1c8-4cef-bc49-571448d0fbaa)

**Comment by pcause** [comment]
yes, restarted.  i just started obsidian after a OS reboot.  create a folder note and no template inserted.  i will try to duplicate in the sandbox with just templater and folder note plugins and see what happens

**Comment by LostPaul** [comment]
> yes, restarted. i just started obsidian after a OS reboot. create a folder note and no template inserted. i will try to duplicate in the sandbox with just templater and folder note plugins and see what happens

Any updates on this?
