### ISSUE TITLE
ctrl (as option) to open folder when clicking

### ISSUE THREAD

**Issue by 1C0D** [LostPaul/obsidian-folder-notes#38]
I watched this plugin last week, and I told myself it could be good to keep the usual way to work with folders and add a new one. Ctrl is not used when clicking on a folder, so it should be a nice option (in settings) to have the possibility to use it to trigger your feature

**Comment by LostPaul** [comment]
So you can collapse folders when clicking normally and with ctrl + click you want to open the folder note? Why not just use the icon next to the folder name to collapse it?

**Comment by LostPaul** [comment]
This will be added with the latest plugin release.
