### ISSUE TITLE
[FR] Support for Excalidraw

### ISSUE THREAD

**Issue by FBarrca** [LostPaul/obsidian-folder-notes#39]
Hello! First and foremost, I'd like to congratulate you on the plugin – I'm a big fan.

I've been experimenting with the canvas feature for the past few months. While it's good, I feel there's room for enhancement. Have you considered integrating Excalidraw drawings? It's a widely-recognized tool, and in my opinion, it offers a more dynamic experience compared to the existing canvases.

**Comment by LostPaul** [comment]
This gave me the idea instead of supporting fixed file types you can allow certain extensions in the settings yourself. It'll decrease the performance though if you choose many file types.

**Comment by LostPaul** [comment]
Done.
