### ISSUE TITLE
suggestion of having the option of canvas or markdown at creation

### ISSUE THREAD

**Issue by ondrobaco** [LostPaul/obsidian-folder-notes#40]
I noticed in settings, there is a possibility to choose to have the note to be either canvas or markdown. 
Is there a technical reason for this?
If not, it would be helpful to be able to choose either canvas or markdown with each new created folder note as 
an option in dropdown submenu. Right after option of "create folder note" could be "create folder canvas"

**Comment by LostPaul** [comment]
> I noticed in settings, there is a possibility to choose to have the note to be either canvas or markdown. Is there a technical reason for this? If not, it would be helpful to be able to choose either canvas or markdown with each new created folder note as an option in dropdown submenu. Right after option of "create folder note" could be "create folder canvas"

It's possible to manually create a canvas folder note when you chose markdown in the settings but a dropdown sounds great.
