### ISSUE TITLE
Folder notes plugin breaks multi-selection of folders

### ISSUE THREAD

**Issue by joellti** [LostPaul/obsidian-folder-notes#42]
I want to report an issue when the plugin is enabled. Before the plugin was enabled, I was able to use Alt key to select multiple folders in File Explorer pane and perform further actions to them. It's no longer possible when the plugin is enabled. Can this function be restored while the plugin is still enabled? Thx

**Comment by joellti** [comment]
Thanks for the quick reply. The toggle was off when I saw the issue. I just tried it again with toggle being on but the issue is still there.

**Comment by LostPaul** [comment]
> Thanks for the quick reply. The toggle was off when I saw the issue. I just tried it again with toggle being on but the issue is still there.

https://github.com/LostPaul/obsidian-folder-notes/assets/70213368/1fac9454-e949-4bd0-84b2-ea23e06fc5ec

**Comment by joellti** [comment]
Really appreciate you for providing this quick video. With that I was able to make it working again

**Comment by cybersader** [comment]
I also had this issue, but that's a nice workaround
