### ISSUE TITLE
Update internal-links when folder name changes

### ISSUE THREAD

**Issue by tes36** [LostPaul/obsidian-folder-notes#44]
My folder structure is this:
/folder/folder.md
/folder/file1.md
/folder/file2.md

file1.md and file2.md have a fileClass property with a wikilink to [[/folder/folder.md]]

If I change /folder/folder.md name it changes succesfully, then appears the error "ENOENT: no such file or directory open" and file1.md and file2.md don't update the wikilink

---
Obsidian v1.4.5

**Comment by LostPaul** [comment]
Should be fixed with the latest release.
