### ISSUE TITLE
what does the "folder path to the overview" mean

### ISSUE THREAD

**Issue by pcause** [LostPaul/obsidian-folder-notes#48]
in the folder overview tab/manage what does the "folder path to overview mean"???

**Comment by LostPaul** [comment]
The default folder path for the folder that should be shown when creating a new folder overview. So when you change it to "folder1" and create a folder overview in a note by either right clicking or using the insert folder overview command (just got released in the lastest version of the plugin) it will show an overview of the folder that you selected in the default settings if you haven't changed the path yet in the settings for the folder overview which is on the edit button.
