### ISSUE TITLE
Broken Links when renaming folder notes

### ISSUE THREAD

**Issue by ThomasSteinbach** [LostPaul/obsidian-folder-notes#49]
When having the settings "General -> Sync folder name" is activated (default), then renaming a folder or its note will break all links to that note.

It looks like a race condition, where both - the folder and the note - were renamed too quickly, such that Obsidian has no time to update the links to the note, while the folder name changes at the same time.

**Comment by LostPaul** [comment]
Same issue as #44

**Comment by LostPaul** [comment]
The latest release should've fixed it. Does it work on your side?

**Comment by ThomasSteinbach** [comment]
@LostPaul yes, seems to work reliably. Many thanks - for the fix and your plugin :)
