### ISSUE TITLE
Collapse indicator doesn't vanish after deleting a file

### ISSUE THREAD

**Issue by Raduq91** [LostPaul/obsidian-folder-notes#51]
I am transitioning from cherrytree to obsidian.
In obsidian I would use just folders(no notes). Can you add a feature so that empty folders(as in no child elements) does not have an .nav-folder-collapse-indicator ?

And there is a issue when creating folder notes(I have 'create folder notes by default on'). When creating new folder there is 50/50 chance that the focus is not on folder name(so I can rename it) but on folder note. 
( clicking 'New folder' at the top of file explorer, or right click on a folder and click on 'New folder')

**Comment by LostPaul** [comment]
The latest plugin release now has the option to hide the collapse indicator.

**Comment by Raduq91** [comment]
Thank you it works, but I have an issue with this kind of setup, the arrow in file explorer is there :
Obsidian Options>Files and Links:
Default Location for new attachments = in subfolder under current folder
Subfolder name = fisiere

(```I use this css snippet to hide the attachments folder 'fisiere' from file explorer:
.nav-folder.mod-root>.nav-folder-children .nav-folder>.nav-folder-title[data-path*="/fisiere"],
.nav-folder.mod-root>.nav-folder-children .nav-folder>.nav-folder-title[data-path*="/fisiere"] + .nav-folder-children{
display: none;} ```)

When I attach files in the folder note it creates the attachment folder(it is hidden with the css snippet) and the .nav-folder-collapse-indicator is there.


And another thing, in a empty folder note, the collapse indicator does not appear if I add something other than a folder, tested with .md, .png and .pdf.

```
Obsidian recognizes the following file formats:

    Markdown files: md.
    Image files: avif , bmp , gif , jpeg , jpg , png , svg , webp.
    Audio files: flac , m4a , mp3 , ogg , wav , webm , 3gp.
    Video files: mkv , mov , mp4 , ogv , webm.
    PDF files: pdf.
    ```

**Comment by LostPaul** [comment]
@Raduq91 Does it work now with the latest plugin release?

**Comment by Raduq91** [comment]
@LostPaul 
For:
```
with this kind of setup, the arrow in file explorer is there :
Obsidian Options>Files and Links:
Default Location for new attachments = in subfolder under current folder
Subfolder name = fisiere

(I use this css snippet to hide the attachments folder 'fisiere' from file explorer: .nav-folder.mod-root>.nav-folder-children .nav-folder>.nav-folder-title[data-path*="/fisiere"], .nav-folder.mod-root>.nav-folder-children .nav-folder>.nav-folder-title[data-path*="/fisiere"] + .nav-folder-children{ display: none;} )

When I attach files in the folder note it creates the attachment folder(it is hidden with the css snippet) and the .nav-folder-collapse-indicator is there.
```
Thanks this works, I attached a pdf and a png file in the folder note, the arrow did not appear.
___
For:
```
And another thing, in a empty folder note, the collapse indicator does not appear if I add something other than a folder, tested with .md, .png and .pdf.
```
Now the behavior is like this. In a empty folder note, the collapse indicator will appear if I add something other than a folder, but if I remove that file( tested with .md .png .pdf) the collapse indicator does not disappear, it will disappear if I restart obsidian.
This is not a problem when adding and removing new folder note inside empty folder note, it works correctly(arrow appears and disappears correctly).


Behavior when obsidian does not recognize a file format, like a .zip file and thus it will not appear in obsidian file explorer:
In an empty folder note if I add a zip file, the collapse indicator will appear, maybe it should not.(and same issue, if I delete the zip file, the collapse indicator will disappear after obsidian restart)


I use community plugin(HTML Reader) that adds support for a new file format .html(it will appear in obsidian file explorer). I use the browser extension SingleFile, it saves a complete webpage in a single .html file.
To take this kind of thing in consideration.

**Comment by LostPaul** [comment]
> Behavior when obsidian does not recognize a file format, like a .zip file and thus it will not appear in obsidian file explorer:
In an empty folder note if I add a zip file, the collapse indicator will appear, maybe it should not.(and same issue, if I delete the zip file, the collapse indicator will disappear after obsidian restart)

This should probably not be a problem for many people for now so it's not really worth fixing right now.

> Now the behavior is like this. In a empty folder note, the collapse indicator will appear if I add something other than a folder, but if I remove that file( tested with .md .png .pdf) the collapse indicator does not disappear, it will disappear if I restart obsidian.
This is not a problem when adding and removing new folder note inside empty folder note, it works correctly(arrow appears and disappears correctly).

I couldn't reproduce this could you add a list of the steps to get it working or even recording of it?

**Comment by Raduq91** [comment]
> > Behavior when obsidian does not recognize a file format, like a .zip file and thus it will not appear in obsidian file explorer:
> > In an empty folder note if I add a zip file, the collapse indicator will appear, maybe it should not.(and same issue, if I delete the zip file, the collapse indicator will disappear after obsidian restart)
> 
> This should probably not be a problem for many people for now so it's not really worth fixing right now.
> 
> > Now the behavior is like this. In a empty folder note, the collapse indicator will appear if I add something other than a folder, but if I remove that file( tested with .md .png .pdf) the collapse indicator does not disappear, it will disappear if I restart obsidian.
> > This is not a problem when adding and removing new folder note inside empty folder note, it works correctly(arrow appears and disappears correctly).
> 
> I couldn't reproduce this could you add a list of the steps to get it working or even recording of it?

https://www.dropbox.com/scl/fi/hbkkrlbne6rz87ptyuyeu/Obsidian_LlNlYV7ZUy.mp4?rlkey=a70mi3iziq7dk6h217v7a0wwr&dl=0

In the beginning, I show the bug I talked about when I first opened the ticket, when creating new folder note there is a high chance that the focus is not on the folder name(to rename it) only on folder note 'untitled 11' the focus was on the name.
