### ISSUE TITLE
[Issue] Folder Overview - Explorer Mode Not Collapsible & Detecting Additional File Extensions

### ISSUE THREAD

**Issue by julroger2013** [LostPaul/obsidian-folder-notes#53]
Hello!

Love your folder note plugin. It definitely overcomes some of the limitations of earlier folder note plugins. 

First, I'm noticing that Folder Overviews, when set to Explorer format, seem not to be collapsible. Is this supposed to be the case? I ask only because one of the options in "Folder overview settings" is "Store collapsed condition." That suggests to me that there should be some collapse/expand ability in the Explorer-style folder overview. Is that right? 

Second, I notice that in the plugin settings, I can add additional file extensions beyond the Obsidian defaults of canvas/markdown/pdf. However, I'm not seeing files with the additional extensions (e.g. docx) appearing in the Explorer-style Folder Overview. Am I doing something wrong? 

On the relevant folder overview, I've modified the "include type" settings to "include all file types." Is there something else that needs to be tweaked?

Thanks for your help, and for making this excellent plugin!

**Comment by julroger2013** [comment]
Ok, I figured out part of the problem! I'm using the ITS theme, which is styled to omit collapse indicators on folders. The File Explorer overview seems to rely on the presence of a collapse indicator. When I switched to a different theme that *did* include collapse indicators, I was able to collapse and expanded folders inside the File Explorer overview. Maybe things can be tweaked so that clicking on a folder name, rather than just the collapse indicator, will collapse and expand?

However, I'm still not able to get non-standard file extensions (pptx, docx, etc.) to appear inside Folder Overviews.

**Comment by julroger2013** [comment]
Slight further update. I went into the ITS theme CSS file and tweaked it so the collapse indicator would appear. When I did so, the Explorer-style overview immediately became collapsible. 

Still cannot get non-standard files to appear in the Explorer-style overview, although they _do_ appear in the list-style overview.

**Comment by LostPaul** [comment]
Both of the issues should now work in the latest plugin release.
