### ISSUE TITLE
create folder note deletes files by mistake

### ISSUE THREAD

**Issue by jiajiala** [LostPaul/obsidian-folder-notes#54]
![image](https://github.com/LostPaul/obsidian-folder-notes/assets/73203026/5e50a84a-2ab6-4078-a206-6e86f0a517de)

This command will delete the note, create a folder and create a new note with the same name

**Comment by LostPaul** [comment]
It doesn't delete the note it just moves it to a different folder and sometimes changes the name of the note. That's the intended behavior of the command.

**Comment by jiajiala** [comment]
![Honeycam 2023-11-07 12-03-35](https://github.com/LostPaul/obsidian-folder-notes/assets/73203026/56bafba2-d723-4b32-93b0-d27966748739)
In fact, it deleted my content

**Comment by LostPaul** [comment]
> ![Honeycam 2023-11-07 12-03-35](https://github.com/LostPaul/obsidian-folder-notes/assets/73203026/56bafba2-d723-4b32-93b0-d27966748739)
> 
> In fact, it deleted my content
> 
> 
> 
> 

Are you using the latest version of the plugin?

**Comment by jiajiala** [comment]
New version fixed
