### ISSUE TITLE
Error creating folder overview

### ISSUE THREAD

**Issue by xubihang** [LostPaul/obsidian-folder-notes#55]
Love using this plugin. Good work. Currently I've been encountering an issue while creating folder overviews in folder notes. Obsidian keeps showing me an error message: "Error creating folder overview (folder notes plugin) - check console for more details." Even though the folder overview is successfully rendered in the note, I still receive this error message every time I open the note.

Also, when folder overviews can't rendered after folder note file created, I try to delete these lines: ' showEmptyFolders: true
onlyIncludeSubfolders: false' then overviews shows (but error message still there😳) 

Here's screen recording: 
https://github.com/LostPaul/obsidian-folder-notes/assets/873649/a47e3dcf-d1ee-40e6-856b-3cffd654fc72

**Comment by LostPaul** [comment]
> Love using this plugin. Good work. Currently I've been encountering an issue while creating folder overviews in folder notes. Obsidian keeps showing me an error message: "Error creating folder overview (folder notes plugin) - check console for more details." Even though the folder overview is successfully rendered in the note, I still receive this error message every time I open the note.
> 
> Also, when folder overviews can't rendered after folder note file created, I try to delete these lines: ' ' then overviews shows (but error message still there😳)
> 
> Here's screen recording: https://github.com/LostPaul/obsidian-folder-notes/assets/873649/a47e3dcf-d1ee-40e6-856b-3cffd654fc72

Open the console and send the error (see https://forum.obsidian.md/t/opening-developer-console/66755)

**Comment by xubihang** [comment]
> > Love using this plugin. Good work. Currently I've been encountering an issue while creating folder overviews in folder notes. Obsidian keeps showing me an error message: "Error creating folder overview (folder notes plugin) - check console for more details." Even though the folder overview is successfully rendered in the note, I still receive this error message every time I open the note.
> > Also, when folder overviews can't rendered after folder note file created, I try to delete these lines: ' ' then overviews shows (but error message still there😳)
> > Here's screen recording: https://github.com/LostPaul/obsidian-folder-notes/assets/873649/a47e3dcf-d1ee-40e6-856b-3cffd654fc72
> 
> Open the console and send the error (see https://forum.obsidian.md/t/opening-developer-console/66755)
[obsidian.md-1698398533887.log](https://github.com/LostPaul/obsidian-folder-notes/files/13187282/obsidian.md-1698398533887.log)

app.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'breakAfter')
    at t.coordsAt (app.js:1:409871)
    at t.scrollIntoView (app.js:1:412248)
    at e.measure (app.js:1:490311)
    at app.js:1:492306
t.coordsAt @ app.js:1
t.scrollIntoView @ app.js:1
e.measure @ app.js:1
(anonymous) @ app.js:1
requestAnimationFrame (async)
e.requestMeasure @ app.js:1
e @ app.js:1
(anonymous) @ app.js:1
e.update @ app.js:1
e.setState @ app.js:1
t.set @ app.js:1
t.set @ app.js:1
t.setViewData @ app.js:1
t.setData @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.loadFileInternal @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.onLoadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.onLoadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.loadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.setViewState @ app.js:1
eval @ plugin:obsidian-kanban:77
o @ plugin:obsidian-kanban:23
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.openFile @ app.js:1
openFolderNote @ plugin:folder-notes:2569
handleFolderClick @ plugin:folder-notes:4624
element.onclick @ plugin:folder-notes:4918
plugin:folder-notes:5089 YAMLParseError: Implicit keys need to be on a single line at line 1, column 1:

title：Folder Overview
^

    at onError (app.js:1:961902)
    at app.js:1:949779
    at oE (app.js:1:950500)
    at mE (app.js:1:961071)
    at app.js:1:962267
    at IE.next [as push] (app.js:1:962409)
    at IE.pop (app.js:1:976596)
    at IE.end (app.js:1:975785)
    at IE.parse (app.js:1:975742)
    at app.js:1:985608
handleOverviewBlock @ plugin:folder-notes:5089
eval @ plugin:folder-notes:5059
t.initDOM @ app.js:1
t.toDOM @ app.js:1
t.sync @ app.js:1
e.sync @ app.js:1
(anonymous) @ app.js:1
e.ignore @ app.js:1
t.updateInner @ app.js:1
t.update @ app.js:1
e.update @ app.js:1
_dispatch @ app.js:1
e.dispatch @ app.js:1
t.set @ app.js:1
t.set @ app.js:1
t.setViewData @ app.js:1
t.setData @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.loadFileInternal @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.onLoadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.onLoadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.loadFile @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.setState @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.setViewState @ app.js:1
eval @ plugin:obsidian-kanban:77
o @ plugin:obsidian-kanban:23
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
v @ app.js:1
t.openFile @ app.js:1
openFolderNote @ plugin:folder-notes:2569
handleFolderClick @ plugin:folder-notes:4624
element.onclick @ plugin:folder-notes:4918

**Comment by LostPaul** [comment]
I can't reproduce it, could you try to replicate it in the sandbox vault and then if it worked send me the vault?

**Comment by LostPaul** [comment]
@xubihang
