### ISSUE TITLE
Command:  create folder note with a new folder note for the active note in the current folder error

### ISSUE THREAD

**Issue by Jacaran** [LostPaul/obsidian-folder-notes#56]
Hi. First of all thank you so much for this great plugin!

When I use the command for "Folder notes: create folder note with a new folder note for the active note in the current folder" it does what it's supposed to do just fine except that the file type gets added to the file name without a period to show that its a file type. Resulting in the folder note note working properly because it is renamed as "foldernotenamemd" instead of "foldernotename.md".
![Screenshot 2023-11-02 235253](https://github.com/LostPaul/obsidian-folder-notes/assets/57670915/6b8df0fa-e85a-4617-9306-817ad50e3aa6)

Sure it's an easy fix if I just manually add a period in front of "md", but still would appreciate it a lot if it just worked.

**Comment by LostPaul** [comment]
Should be fixed now
