### ISSUE TITLE
[bug] Some folder notes appears after plugin update

### ISSUE THREAD

**Issue by silentjames** [LostPaul/obsidian-folder-notes#59]
I have a kinda deep folder structure, like down to level 5 or even lower. Some of folders down below have folder notes - and the notes itself always appear after plugin update and after (not sure) reloading the app. The class `.is-folder-note` is missing for them.
At the same time, this never happen with top-level folder notes - they are always hidden.
<img width="263" alt="Снимок экрана 2023-11-06 в 20 32 51" src="https://github.com/LostPaul/obsidian-folder-notes/assets/12649819/3f337f44-a479-470a-bb9a-aa3a9e29ec26"> <img width="264" alt="Снимок экрана 2023-11-06 в 20 33 28" src="https://github.com/LostPaul/obsidian-folder-notes/assets/12649819/dc08687e-4b54-45f2-8219-235b711c8595">

I'm using macOS Sonoma, and Obsidian 1.4.16 (same installer). Can't exactly name the version of the Folder Notes plugin, because the bug was reproduced even with today's release, 1.6.9.

**Comment by LostPaul** [comment]
Can you try to replicate it in the sandbox vault? I can't reproduce it at all.

**Comment by silentjames** [comment]
Well, kinda yes, but only if I copy that same folder into sandbox vault. Don't know what could be the reason - the structure or the filenames... I can upload the example folder here if you want!

**Comment by LostPaul** [comment]
> Well, kinda yes, but only if I copy that same folder into sandbox vault. Don't know what could be the reason - the structure or the filenames... I can upload the example folder here if you want! 

Sure

**Comment by silentjames** [comment]
[z_Z Правила.zip](https://github.com/LostPaul/obsidian-folder-notes/files/13277361/z_Z.zip)
Here is the archive. Almost all the files names there are in Russian, so it might be a little bit difficult.
You can try this path: z_Z Правила -> VtM v3-v20 -> Дисциплины -> Стойкость, or Стремительность, that's the folders where folder notes always become visible after Obsidian's "reload without saving".

**Comment by LostPaul** [comment]
> [z_Z Правила.zip](https://github.com/LostPaul/obsidian-folder-notes/files/13277361/z_Z.zip) Here is the archive. Almost all the files names there are in Russian, so it might be a little bit difficult. You can try this path: z_Z Правила -> VtM v3-v20 -> Дисциплины -> Стойкость, or Стремительность, that's the folders where folder notes always become visible after Obsidian's "reload without saving".

It seems like mac os did something with the characters because some of them are messed up and I couldn't find the folders you mentioned.

![KlHSQf9gxK](https://github.com/LostPaul/obsidian-folder-notes/assets/70213368/92804bae-f493-4881-9a15-9f3413213208)

**Comment by silentjames** [comment]
Oh... that looks weird. And even with non-messed names - they shouldn't be where they are now...
I made another archive, less files and folder names in English (notes are still in Russian). And the bug can be reproduced - for example, use folder z_Z Rules -> VtM v3-v20 -> Disciplines -> Thaumaturgy -> Path of Blood.
Hope it will work this time xD

**Comment by LostPaul** [comment]
> Oh... that looks weird. And even with non-messed names - they shouldn't be where they are now... I made another archive, less files and folder names in English (notes are still in Russian). And the bug can be reproduced - for example, use folder z_Z Rules -> VtM v3-v20 -> Disciplines -> Thaumaturgy -> Path of Blood. Hope it will work this time xD

Where is "z_Z Rules"? I also couldn't find Disciplines anywhere.

**Comment by silentjames** [comment]
Oh sorry, I forgot to add new archive =\ Shame on me.
[z_Z Rules.zip](https://github.com/LostPaul/obsidian-folder-notes/files/13321622/z_Z.Rules.zip)

**Comment by LostPaul** [comment]
I couldn't reproduce it.
![woc4kau1mCKSbt4Cvfp2](https://github.com/LostPaul/obsidian-folder-notes/assets/70213368/446246fd-88bc-420c-8d1b-2548aedfd6bb)

**Comment by silentjames** [comment]
With this folder, it happens from time to time with folders like "Fortitude" or "Obfuscate", and always with "Path of Blood"...
I know it's been going on for two weeks, but could you please try it one more time? I tried to create more folders (copying the same content, but still), and also renamed some notes for better navigation.
[z_Z Rules.zip](https://github.com/LostPaul/obsidian-folder-notes/files/13403683/z_Z.Rules.zip)
The path will be z_Z Rules -> VtM v3-v20 -> Disciplines -> Thaumaturgy -> z_Z Rules -> VtM v3-v20 -> Disciplines. For the folders there (Celerity, Fortitude, Obfuscate, etc) the bug is always replicated for me.

**Comment by LostPaul** [comment]
It worked for me only when I copied the folder and then looked at the folder notes but after turning the setting to hide the folder notes off and on it works even after I tried to restart Obsidian it still works.
Maybe I can try to replicate it somehow or you find it out but currently I can't reproduce it after I've copied the folder into Obsidian.

**Comment by silentjames** [comment]
Could you please try to delete one of the folder notes there, create new one instead and then reload the Obsidian? Not just restart, but do "Reload app without saving" command? If nothing happens - well, this is the end :)

**Comment by LostPaul** [comment]
> Could you please try to delete one of the folder notes there, create new one instead and then reload the Obsidian? Not just restart, but do "Reload app without saving" command? If nothing happens - well, this is the end :)

Nothing

https://github.com/LostPaul/obsidian-folder-notes/assets/70213368/9bfff0f6-afbd-4896-b156-addc5f3ffe94

**Comment by silentjames** [comment]
Huh, alright then! Hope you can reproduce it one day - or I can find the exact steps. Thank you for all your efforts, and for the great plugin, of course! ❤️
