### ISSUE TITLE
Plugins modified my css, which is not something plugins are supposed to do

### ISSUE THREAD

**Issue by jiajiala** [LostPaul/obsidian-folder-notes#60]
Caused my folder spacing to get bigger
It's causing my folder space to get bigger and that's not what it's supposed to do

**Comment by LostPaul** [comment]
You can avoid this by disabling the setting "disable folder collapsing". But what theme are you using? I might be able to fix it.
![image](https://github.com/LostPaul/obsidian-folder-notes/assets/70213368/4d4de477-1543-4064-9273-0ad46cc79bf2)

**Comment by jiajiala** [comment]
Well, I used my own modified css

**Comment by jiajiala** [comment]
![image](https://github.com/LostPaul/obsidian-folder-notes/assets/73203026/b5aa4fee-da6b-4e0c-a7a0-49ae43aab12c)
There should be no need to modify my css here

**Comment by boltedev** [comment]
I also had to adjust this because the collapse icon padding is pushed down when enabling this addon.
