### ISSUE TITLE
I want the hover window to be triggered when the mouse is placed over the folder as it is over the file

### ISSUE THREAD

**Issue by jiajiala** [LostPaul/obsidian-folder-notes#61]
![Honeycam 2023-11-07 11-32-48](https://github.com/LostPaul/obsidian-folder-notes/assets/73203026/b2a8883c-b6eb-4181-95cf-7743a6050bfd)
Like this, 1, 2, 3 can trigger the suspension window, but test1 can't

Hopefully the folder will trigger the hover window the same way the file did

**Comment by jiajiala** [comment]
I wonder if this request will be considered. Hope to get a reply

**Comment by LostPaul** [comment]
This should work now with the latest plugin version.
