### ISSUE TITLE
After changing the file name, the link breaks

### ISSUE THREAD

**Issue by jiajiala** [LostPaul/obsidian-folder-notes#63]
![Honeycam 2023-11-09 15-52-31](https://github.com/LostPaul/obsidian-folder-notes/assets/73203026/4fa0d1af-7e55-4cd4-ba39-ed214d128e4e)
As shown in the figure, after the note name is modified, the folder name is also changed, but the folder name in the link remains unchanged, resulting in the break of the block connection

**Comment by LostPaul** [comment]
Are you able to reproduce it in the sandbox vault?

**Comment by jiajiala** [comment]
![Honeycam 2023-11-09 21-46-57](https://github.com/LostPaul/obsidian-folder-notes/assets/73203026/a59799df-930d-4223-92ba-aa8ab4966f54)
Figure, stable reproduction in the sandbox
![image](https://github.com/LostPaul/obsidian-folder-notes/assets/73203026/fb7159f3-be6f-4a81-830d-a0fd7af3f656)

**Comment by jiajiala** [comment]
Hope to be able to fix, this plugin does very well, can fix it is perfect

**Comment by LostPaul** [comment]
Does it still happen to you with the latest version?

**Comment by jiajiala** [comment]
fix，thank you
