### ISSUE TITLE
Incorrect Child Note used for folder name in File Explorer with Front Matter Title integration

### ISSUE THREAD

**Issue by dljsjr** [LostPaul/obsidian-folder-notes#64]
After a recent update (not sure when), I noticed that the folder names in the file explorer when using the front matter title integration started to show the wrong note title.

It *appears* that the repro is based on alphabetical sorting:

When using "Inside the folder" storage, if a folder contains a note that has a front matter title override, and this note is before the folder note in the sort order, then that note's title will be used for the folder.

Here's an example clip I made in an empty sandbox vault (w/ folder note hiding disabled):

![CleanShot 2023-11-09 at 08 16 39](https://github.com/LostPaul/obsidian-folder-notes/assets/444635/d247a477-ad2b-4c6e-bc34-1494b0e8ffcf)

**Comment by LostPaul** [comment]
Should be fixed now
