### ISSUE TITLE
[bug] some folder notes under the same name folder `folderA/folderNote/folderNote/folderNote.md`

### ISSUE THREAD

**Issue by Newdea** [LostPaul/obsidian-folder-notes#67]
hi, it's a pretty useful plugin, like it very much.
But I found some folder notes under the same name folder, normally there should be only one level of folder.
For example:
there are some `folderA/folderNote/folderNote/folderNote.md`

should be
`folderA/folderNote/folderNote.md`

**Comment by LostPaul** [comment]
If it can't be reproduced I also can't fix it if you figure out how to reproduce come back but for now I'll close this issue.
