### ISSUE TITLE
Template not being applied

### ISSUE THREAD

**Issue by eytaneeee** [LostPaul/obsidian-folder-notes#68]
Everything is setup correctly for the template (i think) and it doesn't show up. Helpp ! 
![image](https://github.com/LostPaul/obsidian-folder-notes/assets/97612244/023317e6-72b2-460b-86b9-82a9ee461c47)
![image](https://github.com/LostPaul/obsidian-folder-notes/assets/97612244/fa556b6c-6b93-4c56-971f-88ef0de8fa19)
![image](https://github.com/LostPaul/obsidian-folder-notes/assets/97612244/f1e554e2-234b-441f-9a1a-bcfe43f255d6)
![image](https://github.com/LostPaul/obsidian-folder-notes/assets/97612244/5f39bcc6-b2e1-4cf9-b642-e0a40472ec7b)
![image](https://github.com/LostPaul/obsidian-folder-notes/assets/97612244/706dfdc0-d44a-4817-b7dd-b09ec632e458)

**Comment by LostPaul** [comment]
This should work now with the latest release of the plugin.
