### ISSUE TITLE
The collapse button does not appear when there are only folder comments 

### ISSUE THREAD

**Issue by jiajiala** [LostPaul/obsidian-folder-notes#69]
If there are only folder comments and no other files, you want the collapse button not to appear
![image](https://github.com/LostPaul/obsidian-folder-notes/assets/73203026/1761790c-5710-4bca-bf81-5589438c0d20)

**Comment by LostPaul** [comment]
I've added this feature now with the latest release of the plugin. You can choose in the folder overview settings if you want to remove the collapse icon for folder notes that have no other files than the folder note itself.

**Comment by jiajiala** [comment]
> I've added this feature now with the latest release of the plugin. You can choose in the folder overview settings if you want to remove the collapse icon for folder notes that have no other files than the folder note itself.

Folders in the folder list that only have folder comments still have the collapse button
![image](https://github.com/LostPaul/obsidian-folder-notes/assets/73203026/e9281fd6-4889-4c55-9765-821fa6d31bba)

**Comment by LostPaul** [comment]
Oh I just saw that you meant the file explorer I might support that at some time but currently not.
