### ISSUE TITLE
Opening Folder Note prevents collapse/expansion until another note is opened

### ISSUE THREAD

**Issue by sjhorm** [LostPaul/obsidian-folder-notes#71]
Hello!

It seems like this started around the Obsidian v1.5 update. 

If you open a folder note while using a theme without folder arrows you can no longer expand or collapse the folder by clicking on the folder icon until a new note is opened. I attached a video of what's happening. 

https://github.com/LostPaul/obsidian-folder-notes/assets/55192533/ea89069e-e997-4600-8e67-d40fd0fd34ac

Thanks!

**Comment by LostPaul** [comment]
That's what it looks for me when I'm using the ITS theme. Do you have some special settings turned on?
https://github.com/LostPaul/obsidian-folder-notes/assets/70213368/4d05ef16-4469-4708-93f6-33c19655025b

**Comment by sjhorm** [comment]
I'd mentioned the issue to the ITS dev yesterday and she added back in the arrow toggle with the most recent ITS release, which works as a workaround. 

Thanks!

**Comment by LostPaul** [comment]
Alright great
