### ISSUE TITLE
Links to pages beginning with a hashtag

### ISSUE THREAD

**Issue by ThisUserNeedsHelp** [LostPaul/obsidian-folder-notes#72]
I try to create a link to a page using double brackets, thus [[]].

I get [[ParentFolder/#Pagename|#Pagename]].

When I click on the link, I get a new file with the same name as the ParentFolder.

I cannot figure out how to create a working link to the file created by Folder Notes.

**Comment by LostPaul** [comment]
> I try to create a link to a page using double brackets, thus [[]].
> 
> I get [[ParentFolder/#Pagename|#Pagename]].
> 
> When I click on the link, I get a new file with the same name as the ParentFolder.
> 
> I cannot figure out how to create a working link to the file created by Folder Notes.
This is the normal behavior from Obsidian and has nothing to do with the Folder Notes plugin.
![AS1Ob4okicHfiXUktd5t](https://github.com/LostPaul/obsidian-folder-notes/assets/70213368/e5ae346a-79f9-4ee8-88f9-b71494f4bed3)
Or am I missing something here?
