### ISSUE TITLE
Right click wrong behavior

### ISSUE THREAD

**Issue by arteny** [LostPaul/obsidian-folder-notes#76]
When right-click on any folder (with or without folder-note), it expands/collapse it. That is not expected behavior. Please show only context menu. The reason of existing behavior is this plugin, if turn off it, right click works correctly.

**Comment by LostPaul** [comment]
Sorry I forgot to add an if statement but it should work now fine with the latest release.

**Comment by coderlemon17** [comment]
This bug seems to happen again with folder-notes v 1.8.16 and Obsidian v 1.8.10.
