### ISSUE TITLE
Collapse icon doesn't hide or unhide correctly.

### ISSUE THREAD

**Issue by xarx00** [LostPaul/obsidian-folder-notes#80]
This is related to #51. Hiding and unhiding the collapse icon doesn't work correctly.

1. When I have a Folder with folder note and create a New note, the hidden collapse icon doesn't emerge. The new note is then not visible/accessible.

before:
```
                Something
```

create `Note1` under `Something`

after still:
```
                Something
```

2. When I have a single note under a folder and delete it, the collapse icon doesn't hide.

before:
```
                > Something
                            Note 1
```
after:
```
                > Something
```
I use Obsidian 1.5.3 on Windows 10, Folder notes plugin 1.7.11.
I have set Storage location=In the parent folder.

**Comment by LostPaul** [comment]
I didn't specifically tried to fix this bug yet but does this work now with the latest plugin release?

**Comment by xarx00** [comment]
With Folder Notes 1.7.12, problem 1. seems to be fixed. 

Concerning problem 2., it seems to be a feature? I am not sure now, how it should behave.
It seems now that every folder, even an empty one, is marked with the collapse icon. I don't think this is bad, but I'm not sure that it behaved this way in the previous version of the plugin. I think that folders that were either empty or contained only the folder note, didn't have the collapse icon. However, I'm not able to reproduce the behavior now, perhaps it behaved like this only when combined with another plugins..
