### ISSUE TITLE
Rename of a single note renames all parents of the same name

### ISSUE THREAD

**Issue by xarx00** [LostPaul/obsidian-folder-notes#81]
When I have a tree of folders of the same name
```
    Something
        Something
            Something
```
and I rename the innermost note (e.g. Something to Foo), all parents get renamed too
```
    Foo
        Foo
            Foo
```
It doesn't matter whether I rename the note through menu Rename, or by changing its title.

I use Obsidian 1.5.3 on Windows 10, Folder notes plugin 1.7.11.
I have set Storage location=In the parent folder.

**Comment by LostPaul** [comment]
Can you provide a video of the steps to reproduce this? I couldn't get it working.

**Comment by LostPaul** [comment]
Or provide the steps to reproduce it in a sandbox vault?

**Comment by xarx00** [comment]
Unfortunately, I cannot reproduce the exact issue either. Probably it was caused by a combination of plugins.
Instead, Obsidian enters an infinite loop. What I did:

1. I created a new vault
2. I installed you plugin, and configured it:
```
Storage location = In the parent folder
Automatically create folder notes = true
```
3. Then I created the above structucture of folders of the same name with folder notes _outside_
4. Then I tried to rename the innermost folder. 
5. Obsidian started looping:
<img src="https://github.com/LostPaul/obsidian-folder-notes/assets/15482887/352f8ba7-4e3a-4505-863a-e9c880eafc71" width=25% height=25%>

**Comment by LostPaul** [comment]
> Unfortunately, I cannot reproduce the exact issue either. Probably it was caused by a combination of plugins.
> 
> Instead, Obsidian enters an infinite loop. What I did:
> 
> 
> 
> 1. I created a new vault
> 
> 2. I installed you plugin, and configured it:
> 
> ```
> 
> Storage location = In the parent folder
> 
> Automatically create folder notes = true
> 
> ```
> 
> 3. Then I created the above structucture of folders of the same name with folder notes _outside_
> 
> 4. Then I tried to rename the innermost folder. 
> 
> 5. Obsidian started looping:
> 
> <img src="https://github.com/LostPaul/obsidian-folder-notes/assets/15482887/352f8ba7-4e3a-4505-863a-e9c880eafc71" width=25% height=25%>
> 
> 

I also found that while trying to reproduce your bug report and it'll be fixed with the next release.
