### ISSUE TITLE
Some is-collapsed state overridden on startup

### ISSUE THREAD

**Issue by TeuMasaki** [LostPaul/obsidian-folder-notes#82]
Usually Obsidian preserves what folders on outlines are collapsed or not across the session, but recently this plugin started to force unfold some folders on each startup.

Not all folder notes gets this behavior.
I don't think it's related to file names, but folders forcibly unfolded were: C++, OOP, OpenCV, while Blender, HTML, Java and such were unaffected.

Edit: 1.7.5 and prior did not have this bug.

**Comment by LostPaul** [comment]
> Usually Obsidian preserves what folders on outlines are collapsed or not across the session, but recently this plugin started to force unfold some folders on each startup.
> 
> Not all folder notes gets this behavior. Folders forcibly unfolded are: C++, OOP, OpenCV, while Blender, HTML, Java and such were unaffected.
> 
> Edit: 1.7.5 and prior did not have this bug.

Could you provide a video or a way to reproduce this in a sandbox vault? Because I don't know what you mean.

**Comment by TeuMasaki** [comment]
Here is the video. 
First half is expected behavior with version 1.7.5 prior. In the latter half some folders (C++, OOP, OpenCV) uncollapsed itself after a reboot.
https://github.com/LostPaul/obsidian-folder-notes/assets/86175799/dcf8f15b-dd1c-4498-9660-9c4b04f4f89e

**Comment by LostPaul** [comment]
Did the latest plugin release fix it?

**Comment by TeuMasaki** [comment]
It did! Thank you for the fix.
