### ISSUE TITLE
Bug: "Only open folder notes through the name" doesn't work

### ISSUE THREAD

**Issue by frankreporting** [LostPaul/obsidian-folder-notes#83]
I'm seeing two bugs that are appearing specifically with the setting "Only open folder notes through the name." 

- Mobile: Tapping folder note name doesn't actually open the folder note even when this setting is enabled.
- Desktop: Clicking folder note name DOES open folder note. However, after I quit or reload Obsidian, the setting has mysteriously toggled OFF again. I cannot keep this setting enabled past a reload, and I don't see any errors in the console.

I'm on MacOS Sonoma 14.3.1 and Obsidian 1.5.4.

**Comment by LostPaul** [comment]
Update the plugin this bug already has been fixed.
