### ISSUE TITLE
Remove logging

### ISSUE THREAD

**Issue by RyotaUshio** [LostPaul/obsidian-folder-notes#99]
Hi, thank you a lot for this wonderful plugin!

It seems like you forgot to remove this logging code:

https://github.com/LostPaul/obsidian-folder-notes/blob/065000d28e031c35dc36b0b28ca6dae99019d66b/src/ExcludeFolders/functions/folderFunctions.ts#L16-L17

**Comment by LostPaul** [comment]
Yeah I forgot to remove it the next day and I'm currently on vacation so could you create a pr that removes them? Thanks for reporting

**Comment by RyotaUshio** [comment]
Sure, I created one.
